---
- name: install node and npm
  hosts: 178.82.34.23
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm


- name: create new linux user for node app
  hosts: 178.82.34.23
  tasks:
  - name: create linux user
    user:
      name: anil
      comment: anil Admin
      group: admin

       
- name: deploy nodejs app
  hosts: 178.82.34.23
  become: True
  become_user: anil
  tasks:
    - name: unpack nodejs tar file
      unarchive:
        src: C:\Users\anil.kumar.atchi\node-js-app-1.0.0.tgz
        dest: /home/anil
    - name: install dependencies
      npm:
        path: /home/anil/package
    - name: start application
      command:
        chdir: /home/anil/package/app
        cmd: node server
      async: 100
      poll: 0
    - name: ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


 