---
- name: install java and net-tools
  hosts: 23.43.59.34
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install java-8
      apt: name=openjdk-8-jre-headless
    - name: install net-tools
      apt: name=net-tools

- name: Download and install Nexus installer
  hosts: 23.43.59.34
  tasks:
    - name: check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
    - name: untar nexus Installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt
        remote_src: yes
      when: not stat_result.stat.exists
    - name: find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file-type: directory
      register: find_result
    - debug: msg={{find_result}}
    - name: rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists


- name: create nexus user to own nexus folders
  hosts: 23.43.59.34
  tasks:
    - name: ensure group nexus exists
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: make nexus user owner of nexus folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recure: yes


- name: start nexus with nexus user
  hosts: 23.43.59.34
  become: True
  become_user: nexus
  tasks:
    - name: set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^run_as_user=""'
        line: run_as_user="nexus"
    - name: start nexus
      command: /opt/nexus/bin/nexus start

- name: verify nexus running
  hosts: 23.43.59.34
  tasks:
    - name: check with ps
      shell: ps aux | grep nexus
      regsiter: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: pause for one min
      pause:
        minutes: 1
    - name: check with netstat
      shell: netstat -tnlp
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
        
